//Usuario
export const USUARIO_LOGIN = "USUARIO_LOGIN";
export const USUARIO_CERRAR_SESION = "USUARIO_CERRAR_SESION";
export const UPDATE_PREINSCRIPCION = "UPDATE_PREINSCRIPCION";
export const UPDATE_ESTUDIOS = "UPDATE_ESTUDIOS";
export const UPDATE_EXPERIENCIAS = "UPDATE_EXPERIENCIAS";
export const UPDATE_DATOS_EXTRAS = "UPDATE_DATOS_EXTRAS";
export const UPDATE_PREINSCRIPCIONES_VIRTUALES = "UPDATE_PREINSCRIPCIONES_VIRTUALES";

//Alertas
export const ALERTA_SHOW = "ALERTA_SHOW";
export const ALERTA_HIDE = "ALERTA_HIDE";

//MAIN CONTENT
export const MAIN_CONTENT_CARGANDO = "MAIN_CONTENT_CARGANDO";
export const PARA_MOBILE = "PARA_MOBILE";
export const SET_APLICACION_PANEL = "SET_APLICACION_PANEL";